python constrast_cond_gen.py \
--seed 236 \
--use_seed 1 \
--target_text "airplane" \
--constrast_texts "automobile, bird, cat, deer, dog, frog, horse, ship, truck" \
--cond_type "single" \
--cond_scaling 5000 \
--guiding_start 1000 \
--config config_yml/cifar10.yml \
--ckpt model_ckpt/cifar10.ckpt \
--save_path constrast_result/cifar10_constrast_single_0_start_1000_scale_5000
